[package]
name = "nexus-domain"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nexus-error = { path = "../core-error" }
serde.workspace = true
async-trait.workspace = true

[lints]
workspace = true
